[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32dev
framework = arduino

board_build.partitions = huge_app.csv
lib_ldf_mode = deep

build_flags =
  -I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Update/src

lib_deps =
  Networking
  WiFi
  WebServer
  HTTPUpdateServer
  Update
  DNSServer
  Preferences
  EEPROM
  Ticker
  FS
  LittleFS
  SPIFFS
  NetworkClientSecure
  Wire
  SPI
  https://github.com/SUPLA/supla-device.git#v26.4
  milesburton/DallasTemperature@4.0.6
  paulstoffregen/OneWire@2.3.8
  adafruit/Adafruit SSD1306@2.5.17
  adafruit/Adafruit GFX Library@1.12.6
